export const classicSubDesigns = {
  classic1: {
    saveContactStyle: "style4",
    weblinkStyle: "style8",
    weblinkButtonTextColor: "#333333",
    weblinkButtonBackgroundColor: "#333333",
    saveContactBackgroundColor: "#333333",
    saveContactTextColor: "#333333",
    highlightBoxStyle: "style1",
    appIconColor: "",
    boxTextColor: "#333333",
    backgroundColor: "#ffffff",
    boxBackgroundColor: "#333333",
    hideCompanyLogo: false,
    hideSaveContact: false,
    whiteTextAndBorder: false,
  },
  classic2: {
    backgroundColor: "#000000",
    appIconColor: "#5B5B5B",
    whiteTextAndBorder: true,
    saveContactStyle: "style2",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#000000",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#000000",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#000000",
    boxTextColor: "#FFFFFF",
    hideCompanyLogo: false,
    hideSaveContact: false,
  },

  classic3: {
    backgroundColor: "#53B1FF",
    appIconColor: "#53B1FF",
    whiteTextAndBorder: true,
    saveContactStyle: "style2",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#53B2FF",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#333333",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#333333",
    hideCompanyLogo: false,
    hideSaveContact: false,
  },
  classic4: {
    saveContactStyle: "style4",
    weblinkStyle: "style7",
    weblinkButtonTextColor: "#000000",
    weblinkButtonBackgroundColor: "#000000",
    saveContactBackgroundColor: "#000000",
    saveContactTextColor: "#000000",
    highlightBoxStyle: "style1",
    appIconColor: "#ECFF61",
    boxTextColor: "#000000",
    backgroundColor: "#F6FFB4",
    boxBackgroundColor: "#000000",
    hideCompanyLogo: false,
    hideSaveContact: false,
    whiteTextAndBorder: true,
  },
  classic5: {
    saveContactStyle: "style2",
    weblinkStyle: "style4",
    weblinkButtonTextColor: "#ffffff",
    weblinkButtonBackgroundColor: "#FC6C95",
    saveContactBackgroundColor: "#FC6C95",
    saveContactTextColor: "#ffffff",
    highlightBoxStyle: "style2",
    appIconColor: "#FF4775",
    boxTextColor: "#ffffff",
    backgroundColor: "#FF93AE",
    boxBackgroundColor: "#FC6C95",
    hideCompanyLogo: false,
    hideSaveContact: false,
    whiteTextAndBorder: true,
  },
};

export const portraitSubDesigns = {
  portrait1: {
    saveContactStyle: "style4",
    weblinkStyle: "style8",
    weblinkButtonTextColor: "#333333",
    weblinkButtonBackgroundColor: "#333333",
    saveContactBackgroundColor: "#333333",
    saveContactTextColor: "#333333",
    highlightBoxStyle: "style1",
    appIconColor: "",
    boxTextColor: "#333333",
    backgroundColor: "#ffffff",
    boxBackgroundColor: "#333333",
    hideCompanyLogo: false,
    hideSaveContact: false,
    whiteTextAndBorder: false,
  },
  portrait2: {
    saveContactStyle: "style2",
    appIconColor: "#000000",
    backgroundColor: "#333333",
    whiteTextAndBorder: true,
    saveContactBackgroundColor: "#585858",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#585858",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#585858",
    boxTextColor: "#FFFFFF",
    hideCompanyLogo: false,
    hideSaveContact: false,
  },

  portrait3: {
    backgroundColor: "#FFB37C",
    appIconColor: "#FF8731",
    whiteTextAndBorder: true,
    saveContactStyle: "style1",
    saveContactBackgroundColor: "#FF8731",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style7",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#FFFFFF",
    hideCompanyLogo: false,
    hideSaveContact: false,
  },
  portrait4: {
    backgroundColor: "#E8ECFF",
    appIconColor: "#A4A1FF",
    whiteTextAndBorder: false,
    saveContactStyle: "style2",
    saveContactBackgroundColor: "#6560FF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#6560FF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#6560FF",
    boxTextColor: "#FFFFFF",
    hideCompanyLogo: false,
    hideSaveContact: false,
  },
  portrait5: {
    backgroundColor: "#99FF85",
    appIconColor: "#67E14F",
    whiteTextAndBorder: true,
    saveContactStyle: "style3",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style7",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#FFFFFF",
    hideCompanyLogo: false,
    hideSaveContact: false,
  },
  portrait6: {
    backgroundColor: "#47CEFF",
    appIconColor: "#6B8EFF",
    whiteTextAndBorder: true,
    saveContactStyle: "style1",
    saveContactBackgroundColor: "#9AE4FF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style3",
    weblinkButtonBackgroundColor: "#9AE4FF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#9AE4FF",
    boxTextColor: "#FFFFFF",
    hideCompanyLogo: false,
    hideSaveContact: false,
  },
};

export const colorSubDesigns = {
  color1: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "white",
    appIconColor: "",
    whiteTextAndBorder: false,
    saveContactStyle: "style4",
    saveContactBackgroundColor: "#333333",
    saveContactTextColor: "#333333",
    weblinkStyle: "style8",
    weblinkButtonBackgroundColor: "#333333",
    weblinkButtonTextColor: "#333333",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#333333",
    boxTextColor: "#333333",
  },
  color2: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#000000",
    appIconColor: "#515151",
    whiteTextAndBorder: true,
    saveContactStyle: "style3",
    saveContactBackgroundColor: "#F5F5F7",
    saveContactTextColor: "#F5F5F7",
    weblinkStyle: "style7",
    weblinkButtonBackgroundColor: "#F5F5F7",
    weblinkButtonTextColor: "#F5F5F7",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#F5F5F7",
    boxTextColor: "#F5F5F7",
  },
  color3: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#878787",
    appIconColor: "#FFFFFF",
    whiteTextAndBorder: true,
    saveContactStyle: "style3",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style7",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#FFFFFF",
  },
  color4: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#4A0E8A",
    appIconColor: "#9669C6",
    whiteTextAndBorder: true,
    saveContactStyle: "style3",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style7",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#FFFFFF",
  },
  color5: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#50FFCD",
    appIconColor: "#10E0A5",
    whiteTextAndBorder: true,
    saveContactStyle: "style2",
    saveContactBackgroundColor: "#34876F",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#34876F",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#34876F",
    boxTextColor: "#FFFFFF",
  },
  color6: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#72F1FF",
    appIconColor: "#00E6FF",
    whiteTextAndBorder: true,
    saveContactStyle: "style2",
    saveContactBackgroundColor: "#2B6EF6",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#2B6EF6",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#2B6EF6",
    boxTextColor: "#FFFFFF",
  },
};

export const cardSubDesigns = {
  card1: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "",
    whiteTextAndBorder: false,
    saveContactStyle: "style3",
    saveContactBackgroundColor: "#333333",
    saveContactTextColor: "#333333",
    weblinkStyle: "style7",
    weblinkButtonBackgroundColor: "#333333",
    weblinkButtonTextColor: "#333333",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#333333",
    boxTextColor: "#333333",
  },
  card2: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#1F1F1F",
    appIconColor: "#818181",
    whiteTextAndBorder: true,
    saveContactStyle: "style3",
    saveContactBackgroundColor: "#F5F5F7",
    saveContactTextColor: "#F5F5F7",
    weblinkStyle: "style7",
    weblinkButtonBackgroundColor: "#F5F5F7",
    weblinkButtonTextColor: "#F5F5F7",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#F5F5F7",
    boxTextColor: "#F5F5F7",
  },
  card3: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#FFFFD9",
    appIconColor: "#D4FF8E",
    whiteTextAndBorder: false,
    saveContactStyle: "style1",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#333333",
    weblinkStyle: "style8",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#333333",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#333333",
  },
  card4: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#FF9358",
    appIconColor: "#FFC6A8",
    whiteTextAndBorder: true,
    saveContactStyle: "style4",
    saveContactBackgroundColor: "#ffffff",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style8",
    weblinkButtonBackgroundColor: "#ffffff",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style1",
    boxBackgroundColor: "#ffffff",
    boxTextColor: "#FFFFFF",
  },
  card5: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#2FFAD1",
    appIconColor: "#98FFEA",
    whiteTextAndBorder: true,
    saveContactStyle: "style2",
    saveContactBackgroundColor: "#333333",
    saveContactTextColor: "#F5F5F7",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#515151",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#515151",
    boxTextColor: "#FFFFFF",
  },
  card6: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#8E86FF",
    appIconColor: "#C1BDFF",
    whiteTextAndBorder: true,
    saveContactStyle: "style2",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#1807FF",
    weblinkStyle: "style4",
    weblinkButtonBackgroundColor: "#ffffff",
    weblinkButtonTextColor: "#333333",
    highlightBoxStyle: "style2",
    boxBackgroundColor: "#ffffff",
    boxTextColor: "#333333",
  },
};

export const customSubDesigns = {
  image1: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "#5A6A7A",
    whiteTextAndBorder: true,
    saveContactStyle: "style6",
    saveContactBackgroundColor: "#3F5062",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style12",
    weblinkButtonBackgroundColor: "#3F5062",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#3F5062",
    boxTextColor: "#FFFFFF",
  },
  image2: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "#333333",
    whiteTextAndBorder: true,
    saveContactStyle: "style6",
    saveContactBackgroundColor: "#9C9C9C",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style12",
    weblinkButtonBackgroundColor: "#9C9C9C",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#9C9C9C",
    boxTextColor: "#FFFFFF",
  },
  image3: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "",
    whiteTextAndBorder: true,
    saveContactStyle: "style6",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style12",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#FFFFFF",
  },
  image4: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "#2E425C",
    whiteTextAndBorder: true,
    saveContactStyle: "style5",
    saveContactBackgroundColor: "#848484",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style11",
    weblinkButtonBackgroundColor: "#848484",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#848484",
    boxTextColor: "#FFFFFF",
  },
  image5: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "#B5C6FF",
    whiteTextAndBorder: true,
    saveContactStyle: "style6",
    saveContactBackgroundColor: "#042FBE",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style12",
    weblinkButtonBackgroundColor: "#042FBE",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#042FBE",
    boxTextColor: "#FFFFFF",
  },
  image6: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "#5F0067",
    whiteTextAndBorder: true,
    saveContactStyle: "style6",
    saveContactBackgroundColor: "#FFFFFF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style12",
    weblinkButtonBackgroundColor: "#FFFFFF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#FFFFFF",
    boxTextColor: "#FFFFFF",
  },
  image7: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "#76CB6B",
    whiteTextAndBorder: true,
    saveContactStyle: "style6",
    saveContactBackgroundColor: "#F0FFCE",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style12",
    weblinkButtonBackgroundColor: "#F0FFCE",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#F0FFCE",
    boxTextColor: "#FFFFFF",
  },
  image8: {
    hideCompanyLogo: false,
    hideSaveContact: false,
    backgroundColor: "#ffffff",
    appIconColor: "#ffffff",
    whiteTextAndBorder: true,
    saveContactStyle: "style5",
    saveContactBackgroundColor: "#CEDEFF",
    saveContactTextColor: "#FFFFFF",
    weblinkStyle: "style11",
    weblinkButtonBackgroundColor: "#CEDEFF",
    weblinkButtonTextColor: "#FFFFFF",
    highlightBoxStyle: "style3",
    boxBackgroundColor: "#CEDEFF",
    boxTextColor: "#FFFFFF",
  },
};

export const customBackgrounds = {
  image1:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/unsplash_fT6-YkB0nfg%402x%20(1).png?alt=media&token=9748fc68-5d61-447b-b52e-0d7a6d09c504",
  image2:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/unsplash_Yj1M5riCKk4.png?alt=media&token=c3caff99-575f-4a16-ab81-bcae137c2fde",
  image3:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/unsplash_ZGjbiukp_-A.png?alt=media&token=5a6b2e82-6440-4339-a261-bbec25cd3f76",
  image4:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/unsplash_a2kD4b0KK4s.png?alt=media&token=4dac1147-2d32-44bb-b47c-dc1ba6fc9a72",
  image5:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/ashok-acharya-uB4I1Sgpjeg-unsplash%204.png?alt=media&token=241116e8-cb14-4b22-917d-c5f8106916c3",
  image6:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/unsplash_snpFW42KR8I.png?alt=media&token=c43aff57-b1bb-4acf-bbaf-ac77635d4d0f",
  image7:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/unsplash_3BlVILvh9hM.png?alt=media&token=89f92fa0-cddc-4a1c-a251-ee1e74d2e97d",
  image8:
    "https://firebasestorage.googleapis.com/v0/b/yotap-test.appspot.com/o/unsplash_m_7p45JfXQo.png?alt=media&token=91b33d99-0b5c-49a3-9743-796687b38e43",
};
